server:
  port: 8099
  #address: 192.168.202.60
  address: 127.0.0.1


spring:
  servlet:
    multipart:
      max-file-size: 10MB      # 文件上传大小限制，设置最大值，不能超过该值，否则报错
      max-request-size: 10MB     # 文件最大请求限制，用于批量上传
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qvideo-app?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*
qiniu:
  accessKey: 4l6n-solFPMFfHQzcoSiyo8EVTh1Cp71CSQw49DY # 公钥
  secretKey: mhpxrk6EPPbD7c3-83oJ29-UuqdkqipwEUSEXLZ7 # 私钥
  bucketName: blue-shawn  #存储空间名称
  path: http://qvideo.chiou.icu
